input.buttonA.onEvent(ButtonEvent.Down, function () {
    makerController.player1.press(ArcadeButton.A)
    control.runInParallel(function () {
        light.setPixelColor(0, 0x00ffff)
        light.setPixelColor(1, 0x00ffff)
        light.setPixelColor(2, 0x00ffff)
        light.setPixelColor(3, 0x00ffff)
        light.setPixelColor(4, 0x00ffff)
    })
})
// gravity
input.buttonsAB.onEvent(ButtonEvent.Down, function () {
    makerController.player1.press(ArcadeButton.AB)
    control.runInParallel(function () {
        light.setPixelColor(0, 0x00ffff)
        light.setPixelColor(1, 0xff0080)
        light.setPixelColor(2, 0x00ffff)
        light.setPixelColor(3, 0xff0080)
        light.setPixelColor(4, 0x00ffff)
        light.setPixelColor(5, 0xff0080)
        light.setPixelColor(6, 0x00ffff)
        light.setPixelColor(7, 0xff0080)
        light.setPixelColor(8, 0x00ffff)
        light.setPixelColor(9, 0xff0080)
    })
})
// Jetpack
input.buttonB.onEvent(ButtonEvent.Down, function () {
    makerController.player1.setButton(ArcadeButton.B, true)
    control.runInParallel(function () {
        light.setPixelColor(5, 0xff0080)
        light.setPixelColor(6, 0xff0080)
        light.setPixelColor(7, 0xff0080)
        light.setPixelColor(8, 0xff0080)
        light.setPixelColor(9, 0xff0080)
    })
})
input.buttonA.onEvent(ButtonEvent.Up, function () {
    control.runInParallel(function () {
        light.clear()
    })
})
function Sans_Intermediate () {
    music.ringTone(117)
    music.playTone(466, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.stopAllSounds()
    music.ringTone(131)
    music.playTone(831, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.stopAllSounds()
}
// Jetpack
input.buttonB.onEvent(ButtonEvent.Up, function () {
    makerController.player1.setButton(ArcadeButton.B, false)
    control.runInParallel(function () {
        light.clear()
    })
})
input.onGesture(Gesture.FaceDown, function () {
    makerController.player1.press(ArcadeButton.Down)
    control.runInParallel(function () {
        light.setPixelColor(0, 0xffff00)
        light.setPixelColor(1, 0xffff00)
        light.setPixelColor(2, 0xffff00)
        light.setPixelColor(3, 0xffff00)
        light.setPixelColor(4, 0xffff00)
        light.setPixelColor(5, 0xffff00)
        light.setPixelColor(6, 0xffff00)
        light.setPixelColor(7, 0xffff00)
        light.setPixelColor(8, 0xffff00)
        light.setPixelColor(9, 0xffff00)
    })
})
function Sans_Simple (FirstNote: number, LowNote: number) {
    music.ringTone(LowNote)
    music.playTone(FirstNote, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(FirstNote, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(831, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.stopAllSounds()
}
input.onGesture(Gesture.FaceUp, function () {
    makerController.player1.press(ArcadeButton.Up)
    control.runInParallel(function () {
        light.setPixelColor(0, 0x0000ff)
        light.setPixelColor(1, 0x0000ff)
        light.setPixelColor(2, 0x0000ff)
        light.setPixelColor(3, 0x0000ff)
        light.setPixelColor(4, 0x0000ff)
        light.setPixelColor(5, 0x0000ff)
        light.setPixelColor(6, 0x0000ff)
        light.setPixelColor(7, 0x0000ff)
        light.setPixelColor(8, 0x0000ff)
        light.setPixelColor(9, 0x0000ff)
    })
})
// gravity
input.buttonsAB.onEvent(ButtonEvent.Up, function () {
    control.runInParallel(function () {
        light.clear()
    })
})
music.setTempo(150)
music.setVolume(255)
control.runInParallel(function () {
    while (true) {
        Sans_Simple(587, 0)
        Sans_Simple(523, 0)
        Sans_Simple(494, 0)
        Sans_Simple(466, 0)
        Sans_Simple(587, 147)
        Sans_Simple(523, 131)
        Sans_Simple(494, 123)
        Sans_Intermediate()
    }
})
